.github/generate_change_log.sh, .github/workflows/docker-release.yml, .github/workflows/release.yml, CHANGELOG.md, asset/configs/testnet_config/app.toml, asset/configs/testnet_config/client.toml, asset/configs/testnet_config/config.toml, asset/configs/testnet_config/genesis.json
1. Add testnet_config to the release page
2. fix generate_change_log.sh
3. fix license name for docker image labels
n/a
* ci/release
=> ci: add testnet_config to release page and fix issues of release flow

proto/greenfield/storage/events.proto, x/storage/keeper/keeper.go, x/storage/keeper/msg_server.go, x/storage/types/events.pb.go
unify property names in events and DOs:
* OwnerAddress➝Owner
* CreatorAddress➝Creator
* OperatorAddress → Operator
* ...
=> feat: unify property names

x/storage/keeper/keeper.go
If the user creates a bucket on sp1 and then creates an object on sp2, the error message will be more accurate. Use the ErrInvalidApproval error code to indicate an invalid approval from sp.
* AccAddressFromHexUnsafe to MustAccAddressFromHex, to get sp's ApprovalAddress.
* ...
=> fix: add `ErrInvalidApproval` errorcode for sp's approval invalid

deployment/readme.md
Fix wrong script in docs for setting local chain
N/A
./deployment/readme.md
* docs
=> docs: fix localup scripts in document

x/challenge/module_simulation.go
Remove randomized params from challenge module to align other modules.
Randomized params is not used.
NA
* NA
=> fix: remove randomized params from challenge module

e2e/tests/storage_test.go, x/storage/keeper/keeper_test.go, x/storage/keeper/payment.go
Make SP receive storage fee with funding address.
Currently, the storage fee goes to the SP operator address. Change it to the funding address.
NA
* NA
=> feat: make sp receive storage fee with funding addr

CHANGELOG.md
This is a maintenance release.
* [\#195](https://github.com/bnb-chain/greenfield/pull/195) feat: make sp receive storage fee with funding addr  
Please find detailed information in the PR
* No notable changes in this release.
=> release: prepare release v0.1.2 (changelog)

app/app.go, app/upgrade.go
init app with upgrade handlers
the upgrade handlers should be registered after module initialization.
all the handlers functions will be written in `app/upgrade.go`
* app
=> fix: init app with upgrade handlers

x/bridge/types/codec.go, x/payment/types/codec.go, x/sp/types/codec.go, x/storage/types/codec.go
This pr removes the amino dependencies for GetSignBytes and cherries pick the pr:
https://github.com/bnb-chain/greenfield/pull/178
Remove amino dependencies for GetSignBytes
N/A
* remove amino dependencies for GetSignBytes
=> feat: remove amino dependencies for GetSignBytes

x/storage/types/crosschain.go
This pr is to fix the mis-align between greenfield and bsc's definition of update group operation code 
Fix the group operation code
N/A
* modify update group operation code
=> fix: update group operation code

app/app.go, readme.md, swagger/static/swagger.yaml, types/openapiutil/apiconsole.go, types/openapiutil/index.tpl
This pr brings back the swagger server which is deleted by removing the dependency of ignite and updates the swagger.yaml file.
Bring back the swagger server.
n/a
* bring back the swagger server
* updates the swagger.yaml file
=> fix: bring back the swagger server

x/storage/keeper/keeper.go
The returned error message encountered a null pointer access, which caused a panic.
panic error
NA
* NA
=> fix: null pointer access after sp not found

x/challenge/abci.go, x/challenge/keeper/helper.go, x/challenge/keeper/msg_server_test.go
This pr fixes a bug in challenge module.
The code 
```
number := new(big.Int).SetBytes(sdk.Keccak256(seed)[32:])
```
should be
```
number := new(big.Int).SetBytes(sdk.Keccak256(seed[32:]))
```
Otherwise, `number` will always be zero.
Bug fix
NA
* NA
=> fix: fix challenge random issue

swagger/config.json, swagger/static/swagger.yaml
The swagger should show gov v1beta1 apis.
v1beta1 is not being used
NA
* na
=> docs: swagger replace gov v1beta1 by v1

go.mod, go.sum, sdk/client/gnfd_client.go
This pr will replace `github.com/gogo/protobuf ` with `github.com/cosmos/gogoproto`.
Replace `github.com/gogo/protobuf` with `github.com/cosmos/gogoproto`
n/a
* replace github.com/gogo/protobuf with github.com/cosmos/gogoproto
=> fix: replace github.com/gogo/protobuf with github.com/cosmos/gogoproto

CHANGELOG.md, go.mod, go.sum
This release updates the greenfield-cosmos-sdk dependency. Please refer to the [greenfield-cosmos-sdk repository](https://github.com/bnb-chain/greenfield-cosmos-sdk/) for the update details.  
Change log:  
* [#188](https://github.com/bnb-chain/greenfield/pull/188) feat: integrate greenfield with cosmos sdk v0.47 
* [#190](https://github.com/bnb-chain/greenfield/pull/190) feat: add more fields to sp events 
* [#191](https://github.com/bnb-chain/greenfield/pull/191) feat: define the turn for submitting attestation 
* [#197](https://github.com/bnb-chain/greenfield/pull/197) fix: fix e2e issues due to km refactor 
* [#199](https://github.com/bnb-chain/greenfield/pull/199) feat: migrate challenge module to cosmos sdk v0.47 
* [#194](https://github.com/bnb-chain/greenfield/pull/194) feat: fix …
=> release: draft release v0.2.0  

.github/workflows/release.yml
fix go version in the release flow
the go.mod require go1.19+
n/a
* ci/release
=> ci: fix go version in release flow

asset/configs/testnet_config/config.toml, asset/configs/testnet_config/genesis.json
update testnet genesis to v0.1.2
Greenfield testnet has been reset and upgraded to v0.1.2 on 2023/5/12
n/a
* testnet genesis
=> docs: update testnet genesis to v0.1.2

x/storage/keeper/keeper.go
This pr fixes an issue - the deleted objects is not correctly counted in end block when deleting buckets.
Bug fix
NA
* NA
=> fix: correct the counting of deleted objects

proto/greenfield/permission/common.proto, x/permission/types/common.pb.go
If the sub-resources include `grn:o:{bucket_name}/*` in the statement, it indicates that specific permissions is granted to all objects within the specified bucket.
If the sub-resources include `grn:o:{bucket_name}/test_*` in the statement, it indicates that specific permissions is granted to all objects with the `test_` prefix within the specified bucket.
If the sub-resources is empty, it indicates that the permission will not be granted to any object within the specified bucket.
wrong comments
NA
* NA
=> fix: wrong comments in Statements

deployment/localup/localup.sh, e2e/tests/challenge_test.go, e2e/tests/storage_test.go, x/storage/keeper/keeper.go
Issue: new discontinued objects/buckets cannot be deleted due to the wrong deletion of storage keys.
Bug fix
NA
* end block
=> fix: fix discontinued objects/buckets cannot be deleted issue

x/storage/keeper/keeper.go
Fix buckets cannot be deleted when there are more objects than the parameter.
Bug fix
NA
* NA
=> fix: fix discontinue deletion issue

asset/configs/testnet_config/app.toml, asset/configs/testnet_config/config.toml, asset/configs/testnet_config/genesis.json
update testnet genesis to v0.2.1
Greenfield testnet has been reset and upgraded to v0.2.1 on 2023/5/25
n/a
* testnet genesis
=> docs: update testnet assets to v0.2.1

e2e/tests/sp_test.go, x/sp/keeper/sp_storage_price.go
Fix the bug that `QueryGetSecondarySpStorePriceByTime` interface may return wrong data.
The `QueryGetSecondarySpStorePriceByTime` API could previously return data from another SP when the timestamp was before the SP's creation time. This PR corrected the bug by comparing the SP address in the result key with the address in the parameter.
NA
NA
=> fix: QueryGetSecondarySpStorePriceByTime may wrong data

x/payment/keeper/stream_record.go, x/payment/types/types.go, x/storage/abci.go, x/storage/keeper/payment_test.go
Fix the bug that force delete will fail when the payment address is frozen.
Previously, if an account was frozen, any changes to the stream would fail. To prevent this scenario, where an SP might force delete objects or buckets, we added a flag to the context, allowing this action in this specific instance.
NA
NA
=> fix: fail to force delete when the payment addr is frozen

x/bridge/types/codec.go, x/challenge/types/codec.go, x/payment/types/codec.go, x/permission/types/codec.go, x/sp/types/codec.go, x/sp/types/message.go, x/storage/types/codec.go, x/storage/types/message.go
check every module‘s Msg implementation:
- Whether msg is added to the `RegisterInterfaces` method
- `RegisterCodec` is obsolete and has not been processed yet
- Check that all msgs implement the interface of `sdk.Msg`
they were used by GreenfieldScan.
NA
* ...
=> fix: check every module's Msg

x/storage/keeper/keeper.go
Fix bucket cannot be deleted issue when there are discontinued objects in it, it will happen when changing the deletion confirm period parameter smaller.
Bug fix 
NA
* storage keeper
=> fix: fix bucket deletion issue when parameter changed

e2e/core/basesuite.go, e2e/tests/eip712_test.go, sdk/client/tx.go, sdk/client/tx_test.go, sdk/types/types.go, x/storage/abci.go, x/storage/keeper/payment_test.go
add `keyManager` into txOpt, so that allow large batch of txs sent by single client
batch tx sending when switching account
NA
* NA
=> feat: allow user to pass keyManager into Txopt

CHANGELOG.md, go.mod, go.sum
This release enables 2 features:
- record challenge attestation result
- allow user to pass keyManager into Txopt  
* [#267](https://github.com/bnb-chain/greenfield/pull/267) chore: update swagger 
* [#268](https://github.com/bnb-chain/greenfield/pull/268) feat: record challenge attestation result 
* [#271](https://github.com/bnb-chain/greenfield/pull/271) fix: check every module's Msg 
* [#270](https://github.com/bnb-chain/greenfield/pull/270) fix: sp check when reject seal object 
* [#269](https://github.com/bnb-chain/greenfield/pull/269) fix: fix wrong link in readme 
* [#274](https://github.com/bnb-chain/greenfield/pull/274) fix: add sp address check when deposit 
* [#276](https://github.com/bnb-chain/greenfield/pull/276) feat: allow user to pass keyManager into Txopt 
Please find …
=> release: draft release v0.2.2-alpha.2  

x/bridge/keeper/cross_app.go, x/challenge/keeper/msg_server_attest.go, x/challenge/types/params.go
This pr will fix some potential security issues:
+ check the cross-chain refund amount 
Fix some potential security issues
N/A
* fix some potential security issues
=> fix: fix the security issues

x/storage/keeper/keeper.go, x/storage/types/params.go
Update the default value for the parameter `DiscontinueDeletionMax`, which stands for the max objects can be deleted in one block for stop serving.
The previous is too big, considering the content of payment/deletion events is too big.
NA
* parameter
=> fix: update storage discontinue param's default value

e2e/tests/sp_test.go, x/sp/keeper/sp_storage_price.go
This pr will use median price for updating secondary sp price.
Median price is more reasonable than mean price.
NA
* secondary sp price
=> feat: use median store price for secondary sp price

go.mod, go.sum
Changed the cosmos-sdk dependency to use the latest version v0.2.2  
To adapt to the latest release  
none  
none
=> release: prepare release for v0.2.2

asset/configs/testnet_config/config.toml, asset/configs/testnet_config/genesis.json
update testnet genesis to v0.2.2
Greenfield testnet has been reset and upgraded to v0.2.2 on 2023/6/25
n/a
* testnet genesis
=> docs: update testnet assets to v0.2.2

x/sp/types/params.go, x/storage/keeper/keeper.go, x/storage/keeper/payment.go, x/storage/types/types.go
This pr tries to refine the payment code in following aspects:
* update default SecondarySpStorePriceRatio to 0.12
* fix the calculation of secondary sp number for a object (versioned parameter will be further implemented https://github.com/bnb-chain/greenfield/pull/284)
* when simulating object creation, will not check the approval
Make the parameter more sense and fix issues
NA
* parameter SecondarySpStorePriceRatio
=> feat: refine payment and update default parameter

CHANGELOG.md, go.mod, go.sum
This release enables several features and bugfixes.  
* [#279](https://github.com/bnb-chain/greenfield/pull/279) fix: fix the security issues 
* [#280](https://github.com/bnb-chain/greenfield/pull/280) fix: update go.mod to be compatible with ignite 
* [#281](https://github.com/bnb-chain/greenfield/pull/281) feat: add versioned parameters to payment module 
* [#286](https://github.com/bnb-chain/greenfield/pull/286) fix: update storage discontinue param's default value 
* [#287](https://github.com/bnb-chain/greenfield/pull/287) feat: use median store price for secondary sp price 
* [#295](https://github.com/bnb-chain/greenfield/pull/295) add missing field to event 
* [#292](https://github.com/bnb-chain/greenfield/pull/292) feat: allows for setting a custom http client when …
=> release: draft release for v0.2.3-alpha.1

e2e/tests/permission_test.go, x/permission/types/common.go, x/storage/keeper/permission.go, x/storage/keeper/query.go
This PR is to enable the following feature: user can bind a group by name to a resource.
In some scenario we dont know exact the group id of a group, for example the create group message and bind policy policy are in a same tx, but we know the name, so it is much easier to use name instead of ID.
Just make the vaule as:  `grn:g:0xB74AF3aea8F22AbE0683F6D49c9f03c4F8dF449b:xxgroupname`
None
=> feat: add support of group name in policy

x/storage/keeper/keeper.go
This pr will allow simulating bucket creation without approval from storage provider.
For frontend's need, e.g., estimate gas, check whether bucket name exists.
NA
* all simulate without approval
=> feat: allow simulate create bucket without approval

CHANGELOG.md, e2e/tests/permission_test.go, x/permission/types/common.go, x/storage/keeper/keeper.go, x/storage/keeper/permission.go, x/storage/keeper/query.go
This release enables 2 new features.  
* [#301](https://github.com/bnb-chain/greenfield/pull/301) feat: add support of group name in policy  
* [#304](https://github.com/bnb-chain/greenfield/pull/304) feat: allow simulate create bucket without approval  
Please refer to the PRs for detailed information.  
none
=> release: prepare release for v0.2.3-alpha.2

x/virtualgroup/types/params.go
refine gvg staking per bytes and default params
- typo error
- default value does not meet expectations
NA
* NA
=> chore: refine gvg staking per bytes and default params

x/storage/types/params.go
Due to the addition of resumable upload and resumable download functionalities(https://github.com/bnb-chain/greenfield-storage-provider/pull/480 & https://github.com/bnb-chain/greenfield-go-sdk/pull/91 ), we now allow uploading larger files to Greenfield. Therefore, we have increased the value of DefaultMaxPayloadSize from 2GB to 64 GB.
This configuration change allows users to upload files with a maximum size of 64GB to Greenfield. The DefaultMaxPayloadSize parameter defines the maximum payload size that can be handled by the system during file uploads.
NA
NA
=> feat: fix DefaultMaxPayloadSize from 2GB to 64GB

go.mod, go.sum, x/bridge/keeper/cross_app_test.go, x/bridge/keeper/keeper.go, x/bridge/keeper/msg_server_transfer_out.go, x/bridge/types/types.go, x/permission/types/common.go, x/storage/keeper/cross_app_bucket.go, x/storage/keeper/cross_app_group.go, x/storage/keeper/cross_app_object.go, x/storage/keeper/msg_server.go, x/storage/types/crosschain.go
replace rlp with ethereum `abi.encode/decode` in cross-chain transfer
for gas optimization
* replace rlp with ethereum `abi.encode/decode` in cross-chain transferIn and transferOut
* ...
=> feat: replace rlp with abi.encode in cross-chain transfer

e2e/tests/challenge_test.go, x/challenge/keeper/bls_signed_msg.go, x/challenge/keeper/msg_server_attest.go, x/challenge/keeper/msg_server_attest_test.go, x/challenge/types/message_attest.go
This pr will add `chain id` to challenge attestation sign bytes, for preventing replay attacks.
Security fix
NA
* the message to sign is changed
=> fix: add chainid to sign bytes to prevent replay attack

x/challenge/keeper/msg_server_attest.go, x/challenge/keeper/msg_server_attest_test.go, x/storage/keeper/keeper.go
This pr refines challenge module and stop serving for sp exit.
* When force delete bucket, the bucket could be in migration status.
* When attestation submitted, should not slash the sp it it already exit/swapout/...
NA
* challenge attestation
* force delete
=> feat: update challenge and stop serving for sp exit

x/payment/keeper/stream_record.go, x/storage/keeper/keeper.go, x/storage/keeper/payment.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go, x/virtualgroup/keeper/keeper.go, x/virtualgroup/keeper/msg_server.go, x/virtualgroup/keeper/payment.go
This pr fixes some review comments about payment in sp exit pr.
Fix review comments.
NA
* NA
=> feat: fix review comments of sp exit

internal/sequence/sequence.go, x/sp/keeper/sp.go, x/virtualgroup/keeper/keeper.go, x/virtualgroup/keeper/msg_server.go, x/virtualgroup/types/expected_keepers.go
refine the code of migrate bucket and sp exit process
1. add successor sp check
2. Adjust the order of some processes.
NA
* NA
=> chore: refine migrate bucket and sp exit

x/storage/abci.go
This pr will replace panic with error log when delete buckets/objects in end block.
Fix
NA
* end block
=> fix: fix discontinue panic issue

sdk/client/gnfd_client.go, sdk/client/gnfd_tm.go, sdk/client/gnfd_tm_test.go
add tendermint client to sdk and support basic functionality 
direct access to node instead of using abci query back to cosmos sdk
NA
* NA
=> feat: add tendermint to sdk

CHANGELOG.md, go.mod, go.sum
This release adds 6 new features and 2 bugfixes.
Features
* [#315](https://github.com/bnb-chain/greenfield/pull/315) feat: add api for querying lock fee
* [#290](https://github.com/bnb-chain/greenfield/pull/290) feat: replace rlp with abi.encode in cross-chain transfer
* [#323](https://github.com/bnb-chain/greenfield/pull/323) feat: enable asset reconciliation
* [#326](https://github.com/bnb-chain/greenfield/pull/326) feat: add bls verification
* [#336](https://github.com/bnb-chain/greenfield/pull/336) feat: add tendermint to sdk
* [#341](https://github.com/bnb-chain/greenfield/pull/341) feat: support cross chain for multiple blockchains
Bugfixes
* [#307](https://github.com/bnb-chain/greenfield/pull/307) fix DefaultMaxPayloadSize from 2GB to 64GB 
* …
=> release: draft release for v0.2.3-alpha.5

e2e/tests/bridge_test.go, go.mod, go.sum
This pr will add `UpdateChannelPermissions` tx for crosschain module, so we can governance the channel permissions for the crosschain channels.
Add `UpdateChannelPermissions` tx for crosschain module.
n/a
* add UpdateChannelPermissions tx for crosschain module
=> feat: add UpdateChannelPermissions tx for crosschain module

x/sp/client/cli/tx.go, x/sp/keeper/msg_server.go
Add a command for creating storage provider in one transaction, this transaction includes authz the gov module to execute the create  storage provider  message and submit a create  storage provider  proposal.
Merge two messages into one transaction, create new storage provider would be much easier.
```
./build/bin/gnfd tx sp create-storage-provider ../create_storage_provider.json --from funding  --node http://localhost:26750
``` 
* add create storage provider command
=> feat: add create storage provider command

swagger/static/swagger.yaml, x/virtualgroup/client/cli/query.go
add query params command for virtual group
missing command.
$ ./build/bin/gnfd query virtualgroup params --node http://localhost:26750
params:
deposit_denom: BNB
gvg_staking_per_bytes: "16000"
max_global_virtual_group_num_per_family: 10
max_local_virtual_group_num_per_bucket: 0
max_store_size_per_family: "70368744177664"
* add query params command for virtual group
* update swagger
=> feat: add query params command for virtual group

x/storage/types/message.go
this pr adds the validation of `extra` field when creating group, which should not exceed 512. 
To restrict large content on chain
NA
* NA
=> fix: group extra limit

CHANGELOG.md, go.mod, go.sum
This release includes 6 features and 5 bugfixes.
Features:
* [#346](https://github.com/bnb-chain/greenfield/pull/346) feat: Enable websocket client as a option in Greenfield sdk
* [#349](https://github.com/bnb-chain/greenfield/pull/349) feat: add UpdateChannelPermissions tx for crosschain module
* [#350](https://github.com/bnb-chain/greenfield/pull/350) feat: add create storage provider command
* [#357](https://github.com/bnb-chain/greenfield/pull/357) feat: add api to filter virtual group families qualification
* [#352](https://github.com/bnb-chain/greenfield/pull/352) feat: add query params for virtual group
* [#348](https://github.com/bnb-chain/greenfield/pull/348) feat: fix issues and add test cases for payment  
Bugfixes:
* [#351](https://github.com/bnb-chain/greenfield/pull/351) …
=> release: draft release for v0.2.3-alpha.6

cmd/gnfd/cmd/root.go, go.mod, go.sum
This pr will allow node runners to define whether the node will emit events or not.
It is useful for nodes which do not want to emit any events.
new feat
```
Eventing = "everything"
Eventing = "nothing"
```
* new option in app.toml
=> feat: add strategy for event emit

e2e/tests/permission_test.go, types/grn.go, types/grn_test.go
fix parse bucket and object name failed  when object name contains "/"
bufix
```
grn:o::testbucket/test/test2/object
```
* grn ParseBucketAndObjectName
* grn test
=> fix: parse failed when object name contains /

e2e/tests/payment_test.go, e2e/tests/storage_bill_test.go, x/storage/keeper/payment.go, x/storage/keeper/payment_test.go
This pr will fix the storage bill precision issue when there are price change.
The issue is: there is a small difference when calculating bills based on objects vs. calculating bills based on lvgs.
Bug fix
NA
* NA
=> fix: fix the precision issue of storage bill

CHANGELOG.md, go.mod, go.sum
This pr drafts the release v0.2.3-alpha.7, which includes 2 features and 3 bugfixes.
Features:
* [#366](https://github.com/bnb-chain/greenfield/pull/366) feat: add strategy for event emit
* [#368](https://github.com/bnb-chain/greenfield/pull/368) feat: limit sp slash amount and add query api
Bugfixes:
* [#369](https://github.com/bnb-chain/greenfield/pull/369) fix: parse failed when object name contains /
* [#370](https://github.com/bnb-chain/greenfield/pull/370) fix: fix the precision issue of storage bill
* [#371](https://github.com/bnb-chain/greenfield/pull/371) fix: add src dst sp check when migrate bucket
Chores:
* [#365](https://github.com/bnb-chain/greenfield/pull/365) ci: add e2e test coverage report
Draft release
NA
* new features
=> release: draft release for v0.2.3-alpha.7

.github/workflows/e2e-test.yml, Makefile, e2e/core/basesuite.go, e2e/core/config.go
improve e2e tests to  include more coverage from the server side
run the server side(chain) and test case in one process to calculate both coverage
https://github.com/bnb-chain/greenfield/actions/runs/5666030339/attempts/1#summary-15351941848
```
File coverage threshold (80%) satisfied:				FAIL
below threshold:							coverage:	threshold:
app/ante/ante.go							64%		80%
app/export.go								0%		80%
app/genesis.go							0%		80%
app/upgrade.go							75%		80%
cmd/gnfd/cmd/genaccounts.go						8%		80%
cmd/gnfd/cmd/root.go							78%		80%
sdk/client/gnfd_client.go						63%		80%
sdk/client/gnfd_client_option.go					0%		80%
sdk/client/gnfd_tm.go							0%		80%
sdk/client/tendermint_client.go					75%		80%
sdk/client/tx.go							65%		80%
sdk/keys/key_manager.go						79%		80%
types/grn.go								63% …
```
=> fix: improve e2e tests to  include more coverage from server side

deployment/helm/challenger-readme.md, deployment/helm/relayer-readme.md
Add readme for gnfd-relayer and gnfd-challenger helm deployment.
Automate the deployment process and make it customisable for users.
1. `helm repo add bnb-chain https://chart.bnbchain.world/`
2. `helm repo update`
3. `helm install greenfield-validator bnb-chain/gnfd-challenger`
* Update readme
=> add docs for gnfd-challenger and relayer

x/bridge/keeper/cross_app_test.go, x/bridge/types/types.go, x/challenge/abci_test.go, x/virtualgroup/keeper/grpc_query.go
fix error member name in transferInRefundPackageType
error name that caused pkg encode error
* modify `RefundAddr` to `RefundAddress` from transferInRefundPackageType
* ...
=> fix: error member name in transferInRefundPackageType

x/bridge/keeper/cross_app_test.go, x/bridge/types/types.go, x/storage/types/crosschain.go
fix abiencode crosschain package errors
fix bugs
* modify RefundAddr to RefundAddress in transferInRefundPackageType
* modify generalCreateAckPackageArgs to generalDeleteAckPackageArgs in DeleteBucketAckPackage.MustSerialize()
* ...
=> fix: abiencode errors

e2e/tests/payment_test.go, x/payment/keeper/storage_fee_charge.go, x/payment/keeper/stream_record.go, x/payment/keeper/stream_record_test.go
This fix an issue for frozen payment account - lock balance will not be updated when force delete un-sealed object.
Bug fix
NA
* na
=> fix: fix lock balance not updated for frozen payment account

CHANGELOG.md, go.mod, go.sum
This is a official release for v0.2.3, includes all the changes since v0.2.2.
Bugfixes:
* [#375](https://github.com/bnb-chain/greenfield/pull/375) fix: defining err
* [#379](https://github.com/bnb-chain/greenfield/pull/379) fix: error member name in transferInRefundPackageType
* [#383](https://github.com/bnb-chain/greenfield/pull/383) fix: lock balance not updated for frozen payment account
* [#385](https://github.com/bnb-chain/greenfield/pull/385) fix: returned operation type in group cross chain app 
* [#395](https://github.com/bnb-chain/greenfield/pull/395) fix: register gov cross-chain app
Chores:
* [#376](https://github.com/bnb-chain/greenfield/pull/376) chore: add unit tests for the storage module
* [#377](https://github.com/bnb-chain/greenfield/pull/377) chore: improve e2e tests to …
=> release: prepare v0.2.3

x/sp/client/cli/tx.go
allow edit-sp by cmd without blskey
```bash
./bin/gnfd tx sp edit-storage-provider 0x...  --endpoint https://... --home ... --from sp7 --keyring-backend test --node https://...
```
* cmd
=> fix: allow edit-sp by cmd without blskey

asset/configs/testnet_config/app.toml, asset/configs/testnet_config/config.toml, asset/configs/testnet_config/genesis.json
update testnet asset to v0.2.3
* ...
=> docs: update testnet asset to v0.2.3

e2e/tests/permission_test.go, x/payment/keeper/msg_server_test.go, x/permission/keeper/keeper.go, x/storage/keeper/keeper.go, x/storage/keeper/permission.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go
add group existence check when verify permission
Because the expired permission information is not deleted in time, the verification will success, but is expected to failed.
for more information, see stale permission clean in EndBlock. https://github.com/bnb-chain/greenfield/blob/master/x/storage/keeper/keeper.go#L1693-L1728
NA
* add group existence check
* return group id when verify permission in permission module
=> fix: add group existence check when verify permission

x/permission/types/keys.go
fix group member key collision issues
the group id is not fixed length, it may cause the group member key collision.
NA
* NA
=> fix: group member key collision issues

app/app.go, go.mod, go.sum
adapt to cross chain token mintable version
https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/270
Proposal Example:
```json
{
"messages": [
{
"@type": "/cosmos.crosschain.v1.MsgMintModuleTokens",
"authority": "0x7b5Fe22B5446f7C62Ea27B8BD71CeF94e03f3dF2",
"amount": "10000000000000000000000000000"
}
],
"metadata": "",
"deposit": "1000000000000000000BNB",
"title": "Mint CC Token",
"summary": "Mint CC Token"
}
```
Mint Token
```bash
./build/bin/gnfd tx gov submit-proposal ./draft_proposal.json --home ./deployment/localup/.local/validator0 --from validator0 --keyring-backend test --node http://localhost:26750 --fees 1000000000000000000BNB -b sync --gas "200000000" --yes
./build/bin/gnfd tx gov vote 1 yes --home ./deployment/localup/.local/validator0 --keyring-backend test --from …
```
=> chore: adapt to cross chain token mintable version

e2e/core/basesuite.go, x/sp/types/message.go
Previous the proposal can be created while bls key and proof are not valid. this pr adds the validation before submitting the proposal
would waste BNB if invalid proposal allowed to be created. 
* ...
=> fix: validate bls key and proof before submitting proposal

go.mod
update go version in go mod to 1.20
- Some functions like `strings.CutPrefix` only supported in go 1.20
- It already update to go 1.20 in github ci workflows.
NA
* NA
=> chore: Update go version to 1.20 in go.mod

e2e/tests/payment_test.go, x/payment/keeper/auto_settle_record.go, x/payment/keeper/stream_record.go
The `StaticBalance` is positive and `totalRate` is negative. need to use `totalRate.abs()` to calculate the timestamp. 
* ...
=> fix: fix the SettleTimestamp calculation

x/sp/abci_test.go, x/sp/keeper/msg_server_test.go, x/sp/types/message.go, x/storage/keeper/grpc_query.go, x/storage/keeper/keeper.go, x/storage/keeper/payment.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go
this pr fixes that when deleting a object within the reserved period should use ` rate * (LVG stored size diff)` to calculate the fee to avoid deviation. 
* ...
=> fix: fix early deletion fee calculation

e2e/tests/sp_test.go
When checking the global price update, if there is new update from a sp the check is not correct.
Fix test issue
NA
* e2e
=> chore: fix sp e2e test sometimes fail issue

e2e/tests/permission_test.go, x/storage/keeper/msg_server.go, x/storage/types/message.go
It will return error when grant permission to an object with wildcards in the name.
This behavior should be allowed.
```
bucketName: "xxhfsn"
objectName: "*.jpg"
msgPutObjectPolicy := storagetypes.NewMsgPutPolicy(user[0].GetAddr(), types2.NewObjectGRN(bucketName, objectName).String(), types.NewPrincipalWithAccount(user[1].GetAddr()), []*types.Statement{objectStatement}, nil)
s.SendTxBlock(user[0], msgPutObjectPolicy)
```
* err := grn.ParseFromString(msg.Resource, true) // from false to true
=> fix:  grant permission with wildcard objectname

e2e/tests/permission_test.go, x/storage/keeper/msg_server.go, x/storage/types/message.go
It will return error when grant permission to an object with wildcards in the name.
This behavior should be allowed.
```
bucketName: "xxhfsn"
objectName: "*.jpg"
msgPutObjectPolicy := storagetypes.NewMsgPutPolicy(user[0].GetAddr(), types2.NewObjectGRN(bucketName, objectName).String(), types.NewPrincipalWithAccount(user[1].GetAddr()), []*types.Statement{objectStatement}, nil)
s.SendTxBlock(user[0], msgPutObjectPolicy)
```
* err := grn.ParseFromString(msg.Resource, true) // from false to true
=> fix: grant permission with wildcard objectname

x/sp/types/types.go, x/virtualgroup/keeper/msg_server.go
Add sp exit status check when craete gvg
Add sp exit status check when craete gvg
NA
* NA
=> fix: add sp exit status check when craete gvg

app/app.go, x/sp/abci.go, x/sp/abci_test.go
This pr will remove `last block time`. In previous version, the `last block time` is not set when restart, which will cause some issues.
Bug fix
NA
* remove `last block time`
=> fix: fix the last block time is empty issue

x/sp/keeper/msg_server.go
This pr will switch the orders of create sp event and update price event.
If the update price event is emitted ahead of create sp event, it will bring some difficulties for downstream services and dApps.
NA
*NA
=> chore: switch the order of create sp event and update price event

app/app.go, app/upgrade.go, deployment/localup/localup.sh, e2e/tests/payment_test.go, e2e/tests/storage_bill_test.go, go.mod, go.sum, types/openapiutil/apiconsole.go, x/challenge/client/cli/tx_submit.go, x/payment/keeper/msg_server_deposit.go, x/payment/keeper/msg_server_deposit_test.go, x/payment/keeper/payment_account.go, x/storage/client/cli/tx.go
This pr will update the logic of `Deposit` method in the payment module.
Since the payment account is a derived address from the owner address with an index, if users wrongly transfer tokens to the payment address, they cannot get the tokens back for missing the private key. 
This pr will add an additional check for the balance of the payment address for the `Deposit` method, if the balance of the payment account is not zero, the balance of the payment address will be automatically deposited to the payment account.
Deposit the balance of the bank account to the payment account.
n/a
* deposit the balance of the bank account to the payment account
=> feat: deposit the balance of  the bank account to the payment account

x/sp/keeper/msg_server.go
this pr fixes that maintainence address might be empty and it is missing in the `validatebasic()`, causing the chain panic
* ...
=> fix: return err when maintenance addr is not provided

x/challenge/keeper/msg_server_attest.go, x/challenge/keeper/msg_server_submit.go
This reverts commit c6029eea219b6c466255c1ac3a6765fc1422d7db.
Revert this PR, because some of the logic is hardfork, and we did not deal with it yet.
* ...
=> Revert "fix: fix some issues in challenge module (#453)"

CHANGELOG.md, go.mod, go.sum
This release contains 4 features and 4 bugfixes.
Features:
* [#435](https://github.com/bnb-chain/greenfield/pull/435) feat: deposit the balance of the bank account to the payment account
* [#448](https://github.com/bnb-chain/greenfield/pull/448) feat: timelock for large amount withdraw from payment
* [#449](https://github.com/bnb-chain/greenfield/pull/449) feat: complete cdc register
* [#457](https://github.com/bnb-chain/greenfield/pull/457) feat: add api for querying last quota update time
Bugfixes:
* [#451](https://github.com/bnb-chain/greenfield/pull/451) fix: audit issues by verichain
* [#456](https://github.com/bnb-chain/greenfield/pull/456) fix: fix parameter init issue
* [#458](https://github.com/bnb-chain/greenfield/pull/458) fix: correct emit event filed
* …
=> release: draft release for v0.2.5-alpha.1

CHANGELOG.md, x/permission/keeper/keeper.go, x/storage/keeper/grpc_query.go, x/storage/keeper/keeper.go, x/storage/keeper/payment.go, x/storage/keeper/payment_test.go
If policies within one policy group can not be GC within 1 block. We should get rid of policy item which are already handled, and re-persist the policy group.
* ...
=> fix: remaining policies need re-persistence

CHANGELOG.md, x/permission/keeper/keeper.go, x/storage/keeper/grpc_query.go, x/storage/keeper/keeper.go, x/storage/keeper/payment.go, x/storage/keeper/payment_test.go
This release contains 1 bugfix.
https://github.com/bnb-chain/greenfield/pull/465 fix: remaining policies need re-persistence
* #465
=> release: prepare release for v0.2.5-alpha.2

CHANGELOG.md, go.mod, go.sum
This release includes all the changes in the v0.2.5 alpha versions.  
Features:
* [#435](https://github.com/bnb-chain/greenfield/pull/435) feat: deposit the balance of the bank account to the payment account
* [#448](https://github.com/bnb-chain/greenfield/pull/448) feat: timelock for large amount withdraw from payment
* [#449](https://github.com/bnb-chain/greenfield/pull/449) feat: complete cdc register
* [#457](https://github.com/bnb-chain/greenfield/pull/457) feat: add api for querying last quota update time
Bugfixes:
* [#471](https://github.com/bnb-chain/greenfield/pull/471) fix: some issues in challenge module
* [#470](https://github.com/bnb-chain/greenfield/pull/470) fix: testnet block sync issue
* [#451](https://github.com/bnb-chain/greenfield/pull/451) fix: audit issues by …
=> release: draft release for v0.2.5

.github/workflows/build.yml, .github/workflows/docker-release.yml, .github/workflows/gosec.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/tests.yml, CHANGELOG.md, go.mod, go.sum
This release includes all the changes in the v0.2.5 alpha versions.  
Features:
* [#435](https://github.com/bnb-chain/greenfield/pull/435) feat: deposit the balance of the bank account to the payment account
* [#448](https://github.com/bnb-chain/greenfield/pull/448) feat: timelock for large amount withdraw from payment
* [#449](https://github.com/bnb-chain/greenfield/pull/449) feat: complete cdc register
* [#457](https://github.com/bnb-chain/greenfield/pull/457) feat: add api for querying last quota update time
Bugfixes:
* [#471](https://github.com/bnb-chain/greenfield/pull/471) fix: some issues in challenge module
* [#470](https://github.com/bnb-chain/greenfield/pull/470) fix: testnet block sync issue
* [#451](https://github.com/bnb-chain/greenfield/pull/451) fix: audit issues by …
=> release: prepare for release v0.2.5  

x/storage/keeper/keeper.go
Wrong event is emitted for leaving group.
Bug fix
NA
* NA
=> fix: wrong event emitted for leaving group

x/permission/keeper/keeper.go
fix the policy id  not emitted in deletepolicy event
NA
NA
* NA
=> fix: policy id not emit in deletepolicy event

x/challenge/abci.go, x/challenge/abci_test.go, x/challenge/keeper/msg_server_submit.go, x/challenge/keeper/msg_server_submit_test.go, x/challenge/types/expected_keepers.go, x/challenge/types/expected_keepers_mocks.go, x/storage/keeper/msg_server.go, x/storage/keeper/params.go, x/storage/types/expected_keepers_mocks.go
When `segment size` parameter was refactored to versioned parameter, the challenge module was not updated accordingly.
Bug fix
NA
* use versioned parameter
=> fix: use versioned segment size parameter

CHANGELOG.md, go.mod, go.sum
This release contains 3 new bugfixes.
Bugfixes:
* [#478](https://github.com/bnb-chain/greenfield/pull/478) fix: wrong event emitted for leaving group
* [#481](https://github.com/bnb-chain/greenfield/pull/481) fix: policy id not emit in deletepolicy event
* [#482](https://github.com/bnb-chain/greenfield/pull/482) fix: use versioned segment size parameter
Chores:
* [#480](https://github.com/bnb-chain/greenfield/pull/480) chore: improve the validations of parameters
Please find detailed information in the PR
Notable breaking changes:
none
=> release: draft release for v0.2.6-alpha.1  

CHANGELOG.md, go.mod, go.sum
This is a maintenance release to update the cosmos-sdk dependency to the latest version.
To update the cosmos-sdk dependency  
none
none
=> release: prepare release for v0.2.6

CHANGELOG.md
This is a hotfix version to enable the chain to emit deposit events for user accounts and add local virtual group id for related events.
Chores:
* [#489](https://github.com/bnb-chain/greenfield/pull/489) chore: add deposit event for user account
* [#490](https://github.com/bnb-chain/greenfield/pull/490) chore: add lvg id to related events
Please refer to individual PRs for detailed information.  
none
=> release: draft release for v0.2.6-hf.1

x/bridge/keeper/msg_server_update_params.go, x/challenge/keeper/msg_server_update_params.go, x/payment/keeper/msg_server.go, x/permission/keeper/msg_server.go, x/sp/keeper/msg_server.go, x/storage/keeper/msg_server.go, x/virtualgroup/keeper/msg_server.go
Add events when module parameters are changed.
To let the downstream know there are changes about paramters.
```
{
type: "greenfield.storage.Params",
attributes: [
{
key: "bsc_mirror_bucket_ack_relayer_fee",
value: ""250000000000000"",
index: true
},
{
key: "bsc_mirror_bucket_relayer_fee",
value: ""1300000000000000"",
index: true
},
{
key: "bsc_mirror_group_ack_relayer_fee",
value: ""250000000000000"",
index: true
},
{
key: "bsc_mirror_group_relayer_fee",
value: ""1300000000000000"",
index: true
},
{
key: "bsc_mirror_object_ack_relayer_fee",
value: ""250000000000000"",
index: true
},
{
key: "bsc_mirror_object_relayer_fee",
value: ""1300000000000000"",
index: true
},
{
key: "discontinue_bucket_max",
value: ""18446744073709551615"",
index: true
},
{
key: "discontinue_confirm_period",
value: …
```
=> chore: add events for parameter updates

CHANGELOG.md, go.mod, go.sum
This release is the official release for the Greenfield mainnet.
This release contains 1 chore.
Chores:
* [#496](https://github.com/bnb-chain/greenfield/pull/496) chore: add events for parameter updates
NA
* add events
=> release: draft release for v1.0.0

CHANGELOG.md, go.mod, go.sum, x/bridge/keeper/msg_server_update_params.go, x/challenge/keeper/msg_server_update_params.go, x/payment/keeper/msg_server.go, x/permission/keeper/msg_server.go, x/sp/keeper/msg_server.go, x/storage/keeper/msg_server.go, x/virtualgroup/keeper/msg_server.go
This release is the official release for the Greenfield mainnet.
This release contains 1 chore.
Chores:
* [#496](https://github.com/bnb-chain/greenfield/pull/496) chore: add events for parameter updates
NA
* NA
=> release: prepare release for v1.0.0

.github/generate_change_log.sh, .github/workflows/release.yml, asset/configs/mainnet_config/app.toml, asset/configs/mainnet_config/client.toml, asset/configs/mainnet_config/config.toml, asset/configs/mainnet_config/genesis.json
1. add config assets for running fullnode/validator on mainnet network.
2. ci will release packed mainnet config automatically.
Greenfield mainnet launched, new related files added
```
make build
mkdir -p ./.local/config
cp -r ./asset/configs/mainnet_config/* ./.local/config
./build/bin/gnfd start --home ./.local
```
* asset
* ci
=> docs: add mainnet assets

CHANGELOG.md, go.mod, go.sum
This pr prepares release v1.0.1, which is a maintenance release.
Chores:
* [#500](https://github.com/bnb-chain/greenfield/pull/500) chore: add mainnet assets
* [#501](https://github.com/bnb-chain/greenfield/pull/501) chore: add sp price related cli and refine cli and comments
NA
* go mod
* change log
=> release: prepare release for v1.0.1

x/storage/keeper/cross_app_bucket.go, x/storage/types/crosschain.go
This pr is to add missing property `GlobalVirtualGroupFamilyId` to `createBucketPackage`
* add `GlobalVirtualGroupFamilyId` to `createBucketPackage`
=> fix: add `GlobalVirtualGroupFamilyId` to `createBucketPackage`

x/storage/keeper/cross_app_bucket.go, x/storage/types/crosschain.go
This pr is to fix the forward incompatibility of `handleCreateBucketSynPackage`
To make the chain forward compatible
The chain can handle `CreateBucketSynPackage` with or without `GlobalVirtualGroupFamilyId`
* add `handleCreateBucketSynPackageV2`
=> fix: make `handleCreateBucketSynPackage` forward compatible

e2e/tests/permission_test.go, x/permission/keeper/keeper.go
When a account policy is expired, it should be automatically removed from the store with these two mappings:
1.  policyId -> policy
2. policyKey -> policyId
currently `policyKey -> policyId` is missing so that user would fail to re-put policy on the same resource.
When a group policy expired, also need to remove it from the policyGroup. 
* ...
=> fix: policy key is not GC while a expired policy is GC

CHANGELOG.md
This release contains 2 new features, 3 bugfixes and 6 chores.  
Features:
* [#493](https://github.com/bnb-chain/greenfield/pull/493) feat: support reject bucket migration
* [#504](https://github.com/bnb-chain/greenfield/pull/504) feat: add a hardfork for the link to opBNB
Bugfixes:
* [#506](https://github.com/bnb-chain/greenfield/pull/506) fix: add GlobalVirtualGroupFamilyId to createBucketPackage
* [#509](https://github.com/bnb-chain/greenfield/pull/509) fix: make handleCreateBucketSynPackage forward compatible
* [#511](https://github.com/bnb-chain/greenfield/pull/511) fix: policy key is not GC while a expired policy is GC
Chores:
* [#484](https://github.com/bnb-chain/greenfield/pull/484) chore: improve the validations of messages
* …
=> release: draft release for v1.1.0

x/sp/keeper/grpc_query.go
This pr is to optimize the `StorageProviders` method
To prevent traffic from being concentrated on the first sp, we randomly sorted the returned sps list
* shuffle the result of `StorageProviders` query method before return
=> feat: shuffle the result of `StorageProviders` query method

app/upgrade.go, e2e/tests/payment_test.go, e2e/tests/sp_test.go, e2e/tests/storage_bill_test.go, e2e/tests/storage_test.go, e2e/tests/virtualgroup_test.go, x/storage/keeper/keeper.go
In order to disable SP Exit and Bucket migration features for now, this pr removes gas params for below msgs:
1. MsgSwapOut
2. MsgCompleteSwapOut
3. MsgCancelSwapOut
4. MsgStorageProviderExit
5. MsgCompleteStorageProviderExit
6. MsgMigrateBucket
7. MsgCancelMigrateBucket
8. MsgCompleteMigrateBucket
* ...
* ...
=> feat: disable sp exit and bucket migration msg

CHANGELOG.md, go.mod, go.sum
This release introduces the Pampas upgrade to the mainnet. 
Features:
* [#360](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/360) feat: enable Pampas hardfork to mainnet
n/a
none
=> release: prepare release for v1.1.1 

deployment/localup/localup.sh, e2e/tests/virtualgroup_test.go, x/virtualgroup/keeper/keeper.go, x/virtualgroup/keeper/msg_server.go, x/virtualgroup/types/errors.go
This pr contains 2 changes:
1. Creating a GVG should not be identical to others within a virtual group family. 
2. Deleting the last GVG in a Global Virtual Group Family will not result in the deletion of the family. 
Previously, when a family is deleted, all buckets(empty bucket) related to such family still have the stale family info, but actually the family no longer exist, user is not able to re-create objet. This change will keep the empty family and user can  re-create object in the empty bucket. 
* ...
* ...
=> fix: restrict on creating GVG and allow empty family

x/storage/keeper/keeper.go
the bucket status is changed and result in that `EventCancelMigrationBucket` will not be emitted. 
* ...
* ...
=> fix: bucket status causing event emitted

CHANGELOG.md, app/upgrade.go, deployment/localup/localup.sh, go.mod, go.sum, proto/greenfield/storage/tx.proto, x/storage/types/message.go, x/storage/types/tx.pb.go, x/virtualgroup/keeper/keeper.go, x/virtualgroup/keeper/msg_server.go
This PR prepare for the upcoming release v1.2.0
This PR contains:
1. Add the change logs
2. Rename the hardfork to Manchurian
3. Update the cosmos-sdk dep.
None
1. Add setTag transactions;
2. Able to create Object/bucket/Group with tags.
Impact the explorer and metadata service, and also js-sdk
=> docs: prepare for release v1.2.0

app/app.go, x/storage/keeper/cross_app.go, x/storage/keeper/cross_app_permission.go, x/storage/keeper/cross_app_permission_test.go, x/storage/keeper/permission.go, x/storage/types/crosschain.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go, x/storage/types/options.go
Currently, Greenfield supports creating buckets and groups from the smart contracts deployed on BSC/opBNB. This means that the owner of a bucket can be a contract address. However, contract addresses cannot upload objects or put policies under the bucket, resulting in empty buckets owned by smart contracts.
To address this issue, we are going to introduce the cross-chain permission module. With this BEP, smart contracts can grant EOA addresses the ability to upload objects under their buckets, and even support additional functions.
In the current framework, users could only change resource permission on Greenfield. The proposal allows Greenfield users to change resource permission directly on the BSC/opBNB network.
* add permission module
* ...
=> feat: add crosschain permission app

asset/configs/mainnet_config/app.toml, asset/configs/testnet_config/app.toml
fix mainnet/testnet config
Missing `dest-op-chain-id` configuration in app.toml
n/a
* assets
n/a
=> docs: fix mainnet/testnet config

CHANGELOG.md, go.mod, go.sum
This release is to fix the bugs within resource tags in v1.2.0
Bugfixes:
* [#543](https://github.com/bnb-chain/greenfield/pull/543) fix: remove `tags` field from existed msgs
N/A
* remove `tags` field from existed msgs
=> release: prepare release for v1.2.1

CHANGELOG.md, go.mod, go.sum
prepare release v1.2.2
This release introduces the Manchurian upgrade to the mainnet.
n/a
* n/a
* n/a
=> docs: prepare release v1.2.2

CHANGELOG.md
add v1.2.2 changelog
This release introduces the Manchurian upgrade to the mainnet.
n/a
* changelog
* no
=> docs: add v1.2.2 changelog

deployment/localup/localup.sh, go.mod, go.sum, types/grn.go, types/s3util/s3util.go, x/challenge/client/cli/tx_submit.go, x/challenge/types/message_submit.go, x/challenge/types/message_submit_test.go, x/storage/keeper/cross_app_bucket.go, x/storage/keeper/cross_app_bucket_test.go, x/storage/keeper/cross_app_group.go, x/storage/keeper/payment_test.go, x/storage/types/crosschain.go, x/storage/types/message.go, x/storage/types/message_cancel_migrate_bucket.go, x/storage/types/message_complete_migrate_bucket.go, x/storage/types/message_migrate_bucket.go, x/storage/types/message_object_test.go, x/storage/types/message_reject_migrate_bucket.go, x/storage/types/message_test.go
This pr is to change the resource name length limit from bytes length to character length
* change the resource name length limit from bytes length to character length
* related check in sdk
=> feat: change logic of resource name length check

CHANGELOG.md, go.mod, go.sum
this pr prepares for release v1.3.0, introduces the Hulunbeier upgrade to Testnet and Mainnet.
Features:
* [#542](https://github.com/bnb-chain/greenfield/pull/542) feat: add crosschain permission app
* [#534](https://github.com/bnb-chain/greenfield/pull/534) feat: implement Msgs for SP exit
Bugfixes:
* [#552](https://github.com/bnb-chain/greenfield/pull/552) fix: resource account policy key collision
Chore:
* [#551](https://github.com/bnb-chain/greenfield/pull/551) chore: fix typo and update doc
=> release: prepare for release v1.3.0

CHANGELOG.md, go.mod, go.sum
add change log for v1.4.0
This release introduces the Ural upgrade to the testnet.
Features:
* [#560](https://github.com/bnb-chain/greenfield/pull/560) feat: change logic of resource name length check
* [#563](https://github.com/bnb-chain/greenfield/pull/563) feat: set tag by accounts with permission
The logic of resource name length check is changed, downstream service need update.
=> doc: add change log for v1.4.0

deployment/localup/localup.sh, go.mod, go.sum, types/grn.go, types/s3util/s3util.go, x/challenge/client/cli/tx_submit.go, x/challenge/types/message_submit.go, x/challenge/types/message_submit_test.go, x/storage/keeper/cross_app_bucket.go, x/storage/keeper/cross_app_bucket_test.go, x/storage/keeper/cross_app_group.go, x/storage/keeper/payment_test.go, x/storage/types/crosschain.go, x/storage/types/message.go, x/storage/types/message_cancel_migrate_bucket.go, x/storage/types/message_complete_migrate_bucket.go, x/storage/types/message_migrate_bucket.go, x/storage/types/message_object_test.go, x/storage/types/message_reject_migrate_bucket.go, x/storage/types/message_test.go
This pr is to revert the previous modifications made to the resource naming rules
Checking based on character length is not reasonable and may lead to increased storage space usage.
* revert the length restriction from character length to byte length
* update error msgs
* related check in sdk
=> fix: revert the modifications to resource naming rules

go.mod, go.sum, types/grn.go, types/s3util/s3util.go, x/challenge/client/cli/tx_submit.go, x/challenge/types/message_submit.go, x/challenge/types/message_submit_test.go, x/storage/keeper/cross_app_bucket.go, x/storage/keeper/cross_app_bucket_test.go, x/storage/keeper/cross_app_group.go, x/storage/keeper/payment_test.go, x/storage/types/crosschain.go, x/storage/types/message.go, x/storage/types/message_cancel_migrate_bucket.go, x/storage/types/message_complete_migrate_bucket.go, x/storage/types/message_migrate_bucket.go, x/storage/types/message_object_test.go, x/storage/types/message_reject_migrate_bucket.go, x/storage/types/message_test.go
* Revert "feat: change logic of resource name length check (#560)"
This reverts commit eb942972
* chore: update go.mod and some error msgs
revert * Revert "feat: change logic of resource name length check (#560)"
As it is no longer support, we just align with S3
Revert unnecessary PR
None
None
=> fix: revert the modifications to resource naming rules (#568)

x/storage/keeper/keeper.go
In the force delete bucket scenario,  there might be objects being updated, should unlock the shadow object balance. 
* ...
* ...
=> fix: unlock shadow-object balance when a bucket is force deleted

e2e/core/basesuite.go, e2e/tests/storage_test.go, x/payment/keeper/grpc_query_params_by_timestamp.go, x/payment/keeper/grpc_query_test.go, x/payment/keeper/params.go, x/payment/keeper/stream_record.go, x/payment/types/expected_keepers_mocks.go, x/storage/keeper/abci.go, x/storage/keeper/grpc_query.go, x/storage/keeper/grpc_query_test.go, x/storage/keeper/keeper.go, x/storage/keeper/keeper_object_test.go, x/storage/keeper/params.go, x/storage/keeper/params_test.go, x/storage/keeper/payment_test.go, x/storage/types/errors.go, x/storage/types/expected_keepers_mocks.go, x/storage/types/keys.go, x/virtualgroup/types/expected_keepers_mocks.go
* When updating the payment address of a bucket, it is required there is no object in created or updating status.
* Fix GetVersionedParameters is not correct issue.
* Do not allow delete discontinued objects for DeleteObject message. (no DiscontinueObject message on testnet/mainnet. This does not happen on testnet/qa, just to make the logic easier, especially after the feature of updating object content).
Bug fix
NA
* do not allow update payment account when there are objects in created or updating status
* ...
=> fix: disallow update payment address when there are created/updating objects

x/storage/keeper/keeper.go
1. disallow copy an object is being updated
2. an object might be set to OBJECT_STATUS_DISCONTINUED, should not allow sealing on it.
* ...
* ...
=> fix: disallow copy an object is being updated

CHANGELOG.md, go.mod, go.sum
The Greenfield Testnet is expected to have a scheduled hardfork upgrade named Pawnee at block height `6623127`. The current block generation speed forecasts this to occur around 2024/03/27 07:00:00 am +UTC
The Greenfield Mainnet is expected to have a scheduled hardfork upgrade named Pawnee at block height `6239520`. The current block generation speed forecasts this to occur around 2024/04/10  07:00:00 am UTC
* ...
* ...
=> release: prepare for v1.5.0

x/storage/keeper/keeper.go
the `GetLockedObjectCountKey` will not be enabled until Pawnee upgrade. 
* ...
* ...
=> fix: delete after harkfork

x/storage/keeper/keeper.go
This pr will add upgrade check when deleting rate limit status for the bucket.
Add upgrade check when deleting rate limit status.
NA
* dd upgrade check when deleting rate limit status
N/A
=> fix: add upgrade check when deleting rate limit status

app/upgrade.go, deployment/localup/localup.sh, e2e/tests/storage_rate_limit_test.go, e2e/tests/storage_test.go, go.mod, go.sum, x/storage/keeper/keeper.go, x/storage/keeper/payment.go, x/storage/keeper/verify.go
This pr will remove `MsgSetBucketFlowRateLimit` from `Serengeti` upgrade and fix the issue when force-deleting buckets.
Fix uncharge issue when force-deleting objects
n/a
* remove  `MsgSetBucketFlowRateLimit` from `Serengeti` upgrade
*  fix the issue when force-deleting buckets
n/a
=> fix: fix uncharge issue when force-deleting objects

app/upgrade.go, e2e/tests/storage_rate_limit_test.go
This pr will remove `MsgSetBucketFlowRateLimit` from `Serengeti` upgrade.
Remove `MsgSetBucketFlowRateLimit` from `Serengeti` upgrade.
n/a
* remove `MsgSetBucketFlowRateLimit` from `Serengeti` upgrade.
n/a
=> feat: remove set bucket flow rate limit message

CHANGELOG.md, go.mod, go.sum
The Greenfield **Testnet** is expected to have a scheduled hardfork upgrade named Serengeti at block height **7354695**. The current block generation speed forecasts this to occur around 2024/04/18 07:00:00 am +UTC
The Greenfield **Mainnet** is expected to have a scheduled hardfork upgrade named Serengeti at block height **6863285**. The current block generation speed forecasts this to occur around 2024/04/29  07:00:00 am UTC
* ...
* ...
=> release: prepare for v1.6.0 upgrade

app/app.go, app/upgrade.go, x/storage/keeper/cross_app_executor.go, x/storage/keeper/cross_app_executor_test.go, x/storage/types/crosschain.go, x/storage/types/expected_keepers.go
This pr is to add a new crossApp `ExecutorApp` which is used for executing msg from BSC. 
For more information, please refer to [BEP363](https://github.com/bnb-chain/BEPs/pull/363).
* add new cross chain channel `ExecutorChannel` and corresponding cross app `ExecutorApp`
=> feat: add `ExecutorApp`

app/app.go, app/config.go, cmd/gnfd/cmd/root.go, testutil/app.go, x/payment/keeper/stream_record.go, x/storage/keeper/abci.go, x/storage/keeper/keeper.go, x/storage/keeper/payment_check.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go
Check payment data in endblock:
* lock balance
* netflow rate for users
* netflow rate for gvg family/gvg (i.e., income receivers)
This feature should be only enabled for a fullnode which does not provide rpc service - the check is time consuming.
To detect issues in payment module further.
```toml
###############################################################################
###############################################################################
[payment-check]
enabled = true
interval = 50
```
* new logic in end block with panic
* panic if there are issues for the full node
=> feat: add check for payment data

CHANGELOG.md, go.mod, go.sum
The Greenfield Testnet is expected to have a scheduled hardfork upgrade named Erdos at block height 8086093. The current block generation speed forecasts this to occur around 2024/05/10 07:00:00 am +UTC
The Greenfield Mainnet is expected to have a scheduled hardfork upgrade named Erdos at block height 7627845. The current block generation speed forecasts this to occur around 2024/05/22  07:00:00 am UTC
* ...
* ...
=> release: prepare for v1.7.0 upgrade

go.mod, go.sum
The Greenfield Testnet is expected to have a scheduled hardfork upgrade named Erdos at block height 8285529. The current block generation speed forecasts this to occur around 2024/05/16 07:00:00 am +UTC
The Greenfield Mainnet is expected to have a scheduled hardfork upgrade named Erdos at block height 7861456. The current block generation speed forecasts this to occur around 2024/05/29  07:00:00 am UTC
* ...
* ...
=> release: prepare for v1.7.1 upgrade

x/storage/keeper/bucket_rate_limit.go
This pr will add the missing field of `BucketId` for `EventBucketFlowRateLimitStatus`.
Fix the event for `EventBucketFlowRateLimitStatus`.
N/A
* fix EventBucketFlowRateLimitStatus
N/A
=> fix: fix EventBucketFlowRateLimitStatus

x/storage/keeper/payment_check.go
This pr will update payment check to ignore some known issue on test (the issue only happened on testnet).
Fix payment data check.
NA
* update payment check logic
* no impact to fullnodes/validators
=> chore: fix payment check for testnet

readme.md
update the references to the old website in the repository with links to the new website (https://docs.bnbchain.org/bnb_greenfield/)
N/A
N/A
* update the references to the old website in the repository with links to the new website (https://docs.bnbchain.org/bnb_greenfield/)
* N/A
=> docs: replace docs link

CHANGELOG.md, go.mod, go.sum
The Greenfield Testnet is expected to have a scheduled hardfork upgrade named `Veld` at block height 9581218. The current block generation speed forecasts this to occur around 2024/06/25 07:00:00 am +UTC
The Greenfield Mainnet is expected to have a scheduled hardfork upgrade named `Veld` at block height 9269910. The current block generation speed forecasts this to occur around 2024/07/08  07:00:00 am UTC
* ...
* ...
=> release: prepare for v1.8.0

x/virtualgroup/keeper/grpc_query.go
initial val for min value comparison should be large enough
* ...
* ...
=> fix: initial val for min value comparison should be large enough

app/upgrade.go, deployment/localup/localup.sh, go.mod, go.sum, proto/greenfield/permission/types.proto, x/permission/types/types.pb.go, x/storage/keeper/cross_app_permission.go, x/storage/keeper/cross_app_permission_test.go, x/storage/keeper/keeper.go, x/storage/keeper/permission.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go
1. Cross-chain policy creation supports msg
2. Remove cross-chain operation restrictions https://docs.google.com/spreadsheets/d/1CH2W0kNgQXwQIhQybdcxaeKm4QtEnse_3tuMd0u6zAQ/edit?gid=0#gid=0
=> feat: Support msg to create policy by cross chain

CHANGELOG.md, app/upgrade.go, go.mod, go.sum
The Greenfield Testnet is expected to have a scheduled hardfork upgrade named Mongolian
 at block height 10780238. The current block generation speed forecasts this to occur around 31 July 2024 07:00:00  UTC
The Greenfield Mainnet is expected to have a scheduled hardfork upgrade named Mongolian
 at block height 10314605. The current block generation speed forecasts this to occur around 08 Aug 2024 07:00:00 UTC
=> release: prepare for v1.9.0

app/upgrade.go, deployment/localup/localup.sh, e2e/tests/payment_test.go, go.mod, go.sum, x/payment/keeper/stream_record.go
Fix the issue - fail to resume frozen payment account when netflow is zero.
Upgrade
NA
* payment deposit
=> fix: fail to resume frozen payment account when netflow is zero

CHANGELOG.md, go.mod, go.sum
This release introduces the Savanna upgrade.
Fixes:
https://github.com/bnb-chain/greenfield/pull/647 fix: fail to resume frozen payment account when netflow is zero
=> release: prepare for v1.10.0

.github/workflows/lint.yml, x/virtualgroup/keeper/msg_server.go
Update the rule of gvg updateParams to allow GvgStakingPerBytes change.
We want to reduce the cost of SP staking when create and expand size of gvg.
N/A
* gvg updateParams allowance check
* gvg updateParams when send in proposal
=> feat: allow change GvgStakingPerBytes for gvg updateParams

CHANGELOG.md
This release contains 1 new feature.
Features:
https://github.com/bnb-chain/greenfield/pull/655 feat: allow change GvgStakingPerBytes for gvg updateParams
=> release: prepare for v1.10.1
