bnb-chain/greenfield

e2e/tests/storage_test.go, sdk/client/gnfd_client.go
sdk: fix tmclient is not init 
inject tmclient
NA
* NA
=> fix: init tmclient

deployment/localup/localup.sh
add export script for sp development
NA
bash ./deployment/localup/localup.sh export_sps 1 1
```
{
"sp0": {
"OperatorAddr": "0x14539343413EB47899B0935287ab1111Df891d04",
"FundingAddr": "0x21c6ff21DD7012DE1CCf9055f2eB234A44a1d3fB",
"SealAddr": "0x8e424c6Db42Ad9A5d91b24e20b5f603eC70abbA3",
"ApprovalAddr": "0x7Aa5C8B50696f1D15B3A60d6629f7318c605bb4C",
"GcAddr": "0xfa238a4B262e1dc35c4970A2296A2444B956c9Ca",
"OperatorPrivKey": "ba6e97958d9c43d1ad54923eba99f8d59f54a0c66c78a5dcbc004c5c3ec72f8c",
"FundingPrivKey": "bd9d9e7823cd2dc7bc20f1b6676c3025cdda6cf5a8df9b04597fdff42c29af01",
"SealPrivKey": "aacd6b834627fdbc5de2bfdb1db31be0ea810a941854787653814c8040a9dd39",
"ApprovalPrivKey": "32108ed1a47c0af965824f84ac2162c029f347eec6d0988e642330b0ac264c85",
"GcPrivKey": …
```
=> feat: add export key for localup script

e2e/tests/challenge_test.go, e2e/tests/storage_test.go, x/storage/types/params.go
This pr cherry-picks the changes of :
* https://github.com/bnb-chain/greenfield/pull/179
It also fix other issues cause by km refactor.
Fix
NA
* e2e testcases
=> fix: fix e2e issues due to km refactor

e2e/core/basesuite.go, e2e/tests/challenge_test.go
This updates challenge e2e tests to align the cosmos-sdk migration.
Fix e2e tests
NA
* NA
=> feat: migrate challenge e2e tests

app/ante/ante_test.go, app/ante/utils_test.go, sdk/client/tx.go
This pr is to fix the ante test part after migrating  cosmos-sdk to v0.47.0
* no notable changes
=> chore: fix ante test

.github/workflows/build-test.yml, .github/workflows/e2e-test.yml, .github/workflows/gosec.yml, .github/workflows/lint.yml, Dockerfile, app/app.go, sdk/client/tx.go, x/challenge/keeper/grpc_query_test.go, x/challenge/keeper/msg_server_test.go, x/challenge/types/message_update_params_test.go
This pr will update the github workflows to run ci jobs for every pull request.
Run ci jobs for every pull request
n/a
* run ci jobs for every pull request
=> ci: run ci jobs for every pull request

sdk/client/gnfd_client.go
this pr fixes the  cmtclient init issue
fix init issue
NA
* Na
=> fix: migrate sdk fix to v0.47_latest

deployment/readme.md
This pr cherries pick the changes from https://github.com/bnb-chain/greenfield/pull/182.
Fix localup scripts in the document
N/A
* Fix localup scripts in the document
=> docs: fix localup scripts in document

deployment/localup/localup.sh
Cherry pick #180  to develop_v0.47
NA
NA
* NA
=> feat: add export key for localup script (#180)

Makefile, deployment/localup/localup.sh, e2e/tests/gashub_test.go
This pr will fix the gashub e2e tests.
Fix unit test for gashub
n/a
* fix e2e test for gashub
=> fix: fix e2e test for gashub

e2e/tests/permission_test.go, x/storage/keeper/permission.go, x/storage/keeper/query.go
cherry pick https://github.com/bnb-chain/greenfield/pull/187 to develop_v0.47
NA
NA
* NA
* ...
=> feat: support empty operator for verifypermission (cherry pick #187)

types/errors/errors.go, x/sp/client/cli/query.go, x/sp/client/cli/query_params.go, x/sp/client/cli/tx.go, x/storage/client/cli/flags.go, x/storage/client/cli/query.go, x/storage/client/cli/query_params.go, x/storage/client/cli/tx.go
cherry pick https://github.com/bnb-chain/greenfield/pull/185 to develop_v0.47
NA
NA
* NA
* ...
=> fix: sp & storage & permission module's cli bug (cherry pick #185)

cmd/gnfd/cmd/root.go
Change the default log time format to show milliseconds.
default time format for `zerolog` does not show the milliseconds, override it to enable the feature.
* logger
=> feat: change the default log time format to show milliseconds

e2e/tests/gensp_test.go, x/sp/keeper/slash.go, x/sp/keeper/sp_test.go
sp staking ledger error when slash
NA
NA
* NA
=> fix: sp staking ledger error when slash

go.mod, go.sum, swagger/static/swagger.yaml
This pr will update the swagger file based on the latest cosmos-sdk. 
Update swagger file based on the latest cosmos-sdk.
n/a
* update swagger file based on the latest cosmos-sdk
=> fix: update swagger file based on the latest cosmos-sdk

deployment/docker/README.md, deployment/docker/docker-compose.yaml
adding docker-compose component to ease visibility
To reduce complexity of spinning up the testnet env
Automated process on spinning up testnet env
added docker-compose and its respective ReadME
=> added docker compose

e2e/core/basesuite.go
implemented changes according to the feedback in the security report  
issues such as overflow errors were raised  
none  
please refer to the security report and the changed files
=> fix: security report fix  

go.mod, go.sum, swagger/config.json, swagger/static/swagger.yaml
This pr is to update the swagger file
* add gashub module to the swagger
=> chore: update swagger

deployment/localup/create_sp.json, e2e/tests/storage_test.go, types/grn.go, x/sp/keeper/sp_test.go, x/storage/keeper/keeper.go
fix sp existence check when reject seal object add e2e test for reject seal
NA
NA
* NA
=> fix: sp check when reject seal object

readme.md
This pr will fix the wrong link in readme.
Fix link
NA
* readme.md
=> fix: fix wrong link in readme

swagger/static/swagger.yaml, x/sp/keeper/msg_server.go, x/sp/types/errors.go, x/sp/types/message.go
add sp address check when deposit
NA
NA
* NA
=> fix: add sp address check when deposit

.github/workflows/buf.yml, Makefile, e2e/tests/bridge_test.go, go.mod, go.sum
This pr will update the `go.mod` to be compatible with ignite cli. 
Update go.mod to be compatible with ignite
n/a
* update go.mod to be compatible with ignite
=> fix: update go.mod to be compatible with ignite

x/virtualgroup/keeper/payment.go, x/virtualgroup/types/expected_keepers.go, x/virtualgroup/types/expected_keepers_mocks.go
Use payment high level interface to simplify codes in virtual group module.
Refine codes
NA
* NA
=> chore: refine payment for gvg settle

swagger/static/swagger.yaml
update swagger 
some api interface is missing in swagger file
NA
* NA
=> fix: update swagger file for virtual group dev

readme.md
Perform wording change for binance related terms
none
none
none
=> chore: bnb wording change

go.mod, go.sum
update greenfield-cometbft-db version(develop)
* ...
=> chore: update greenfield-cometbft-db version

app/ante/utils_test.go, deployment/localup/localup.sh, deployment/readme.md, go.mod, go.sum, x/gensp/gentx_test.go
add signature verification for `BLS` key when creating, editing the validator.
[add a  `Proof of Possession` to ensure the validator holds the `BLS` key.](https://github.com/bnb-chain/greenfield-cosmos-sdk/pull/239)
* cli
=> feat: add bls verification

x/payment/keeper/keeper.go, x/payment/keeper/stream_record.go, x/storage/keeper/payment.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go, x/virtualgroup/types/expected_keepers_mocks.go
This pr will charge object store fee if the storage duration is less than reserve time, which is 6 months by default.
New feature
NA
* charge when delete object
=> feat: charge at least reserve time for storing objects

app/app.go, app/reconciliation.go
This pr will add payment reconciliation feature.
Add payment reconciliation to make sure the netflow rate change is correct in each block.
NA
* endblock
=> feat: add payment flow rate recon

.github/workflows/buf.yml, Makefile, scripts/protoc-swagger-gen.sh, swagger/static/swagger.yaml
Add swagger check
Ensure the swagger files are up to date
make proto-swagger-check
* NA
=> chore: add swagger check

go.mod, go.sum
The current build can not pass, fix it.
None
=> fix: update go mod

x/storage/types/errors.go
fix defining a error in another module.
* ...
=> fix: defining err

x/challenge/abci_test.go, x/challenge/keeper/grpc_query_test.go, x/challenge/keeper/msg_server_attest_test.go, x/challenge/keeper/msg_server_submit_test.go, x/challenge/keeper/slash_test.go
This pr will add some unit test cases for challenge module.
add uts
NA
* NA
=> chore: add unit test cases for challenge module

x/storage/keeper/cross_app_group.go
This pr will fix the returned operation type in the group cross-chain app.
Fix the returned operation type in the group cross-chain app.
n/a
* fix the returned operation type in the group cross-chain app
=> fix: fix returned operation type in group cross chain app

x/payment/keeper/auto_resume_record_test.go, x/payment/keeper/auto_settle_record.go, x/payment/keeper/auto_settle_record_test.go, x/payment/keeper/grpc_query_test.go, x/payment/keeper/msg_server_create_payment_account_test.go, x/payment/keeper/msg_server_deposit_test.go, x/payment/keeper/msg_server_disable_refund_test.go, x/payment/keeper/msg_server_test.go, x/payment/keeper/msg_server_withdraw_test.go, x/payment/keeper/payment_account_count.go, x/payment/keeper/payment_account_count_test.go, x/payment/keeper/payment_account_test.go, x/payment/keeper/price_test.go, x/payment/keeper/storage_fee_charge_test.go, x/payment/keeper/stream_record_test.go
This pr will add some unit test cases for payment module.
add uts
NA
* NA
=> chore: add unit test cases for payment module

app/app.go
This pr will register the gov cross-chain app.
Register the gov cross-chain app
N/A
*  register gov cross-chain app
=> fix: register gov cross-chain app

deployment/localup/localup.sh, e2e/tests/payment_test.go, e2e/tests/storage_bill_test.go, x/storage/keeper/payment_test.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go
This pr will add more e2e test cases for payment related module.
Add more e2e
NA
* more e2e cases
=> chore: add more e2e test cases for payment module

readme.md
update document site links
* readme.md
=> docs: update document site links

x/bridge/types/params.go, x/storage/types/params.go
=> chore: modify default gas

go.mod, go.sum, swagger/static/swagger.yaml, x/bridge/keeper/genesis_test.go, x/storage/types/params.go
This pr will update the dependencies to the latest develop branch.
Update the dependencies to the latest develop branch.
n/a
* update the dependencies to the latest develop branch
=> fix: update the dependencies to the latest develop branch

deployment/localup/localup.sh, go.mod, go.sum, x/gensp/client/cli/gentx.go
skip sig verification on genesis block
the `antehandler` will skip sig verification on the genesis block.
* genesis
=> feat: skip sig verification on genesis block

CHANGELOG.md, go.mod, go.sum
This release contains 4 features and 4 bugfixes.    
Features:
* [#411](https://github.com/bnb-chain/greenfield/pull/411) feat: add
* [#413](https://github.com/bnb-chain/greenfield/pull/413) feat: implement cross-chain mechanism between op and greenfield
* [#415](https://github.com/bnb-chain/greenfield/pull/415) feat: enable plain store for full node
* [#420](https://github.com/bnb-chain/greenfield/pull/420) feat: skip sig verification on genesis block
Bugfixes:
* [#416](https://github.com/bnb-chain/greenfield/pull/416) fix: update the dependencies to the latest develop branch
* [#419](https://github.com/bnb-chain/greenfield/pull/419) fix: validate bls key and proof before submitting proposal
* [#410](https://github.com/bnb-chain/greenfield/pull/410) fix: fix group member key collision …
=> release: draft release for v0.2.4-alpha.2

CHANGELOG.md, go.mod, go.sum
Update dependencies for cosmos math/api  
Fix release ci error  
none  
none
=> chore: update dependencies for cosmos math/api

Dockerfile
rm bash and curl for security concern
=> fix: rm bash and curl for dockerfile

CHANGELOG.md
=> doc: add changelog

x/sp/types/types.go, x/virtualgroup/keeper/msg_server.go
* add sp exit status check when create gvg and swapout
* allow sp in maintenance can create gvg
[SP is exiting, commit GVG include SP, create successful](https://app.clickup.com/t/865cz3x0d)
NA
* NA
=> fix: add sp exit status check when craete gvg (#433)

x/virtualgroup/keeper/msg_server.go
When secondary sp in GVG is exiting 
NA
NA
* NA
=> fix: add secondary sp exit status check

go.mod, go.sum
This pr will bump cosmos sdk to include a bug fix.
Bug fix
NA
* go.mod
=> chore: bump cosmos sdk version

x/payment/keeper/msg_server_withdraw.go, x/payment/keeper/payment_account.go, x/payment/keeper/storage_fee_charge.go, x/payment/keeper/stream_record.go
This pr will fix some issues in payment modules, including typos and incorrect comparisions. 
Fix
NA
* NA
=> fix: fix some issues in payment module

asset/configs/testnet_config/app.toml, asset/configs/testnet_config/config.toml, asset/configs/testnet_config/genesis.json
update testnet asset to v0.2.4
* ...
=> docs: update testnet asset to v0.2.4

sdk/types/codec.go
=> feat: complete cdc register

types/grn.go, x/permission/keeper/keeper.go, x/permission/types/types.go, x/storage/keeper/msg_server.go
fix audit issues by verichain
NA
NA
* NA
=> fix: audit issues by verichain

x/challenge/keeper/msg_server_attest.go, x/challenge/keeper/msg_server_submit.go
Fix some issues in challenge module.
Improve code quality
NA
* NA
=> fix: fix some issues in challenge module

proto/greenfield/sp/tx.proto, x/sp/client/cli/tx.go, x/sp/types/tx.pb.go, x/sp/types/types.go, x/storage/keeper/keeper.go
this pr fix event not emitting  correct field 
SP need to persist correct attribute into DB 
* ...
=> fix: correcting events field

app/upgrade.go, go.mod, go.sum, x/payment/module.go
This pr will fix genesis block app hash mismatch issue.
Bug fix
NA
* NA
=> fix: app hash mismatch for genesis block

x/payment/keeper/msg_server_withdraw.go
Fix testnet chain blocksync issue.
Bug fix
NA
* NA
=> fix: testnet block sync issue

x/challenge/keeper/msg_server_attest.go, x/challenge/keeper/msg_server_submit.go
Fix some issues in challenge module.
Improve code quality
NA
* NA
=> [R4R] fix: fix some issues in challenge module

CHANGELOG.md
Bugfixes:
* [#470](https://github.com/bnb-chain/greenfield/pull/470) fix: testnet block sync issue
* [#471](https://github.com/bnb-chain/greenfield/pull/471) fix: some issues in challenge module
None
None
Just doc
=> docs: add change log for v0.2.5-alpha.3

CHANGELOG.md, x/challenge/keeper/msg_server_attest.go, x/challenge/keeper/msg_server_submit.go, x/payment/keeper/msg_server_withdraw.go
This release contains 2 bugfixes.
Bugfixes:
* [#470](https://github.com/bnb-chain/greenfield/pull/470) fix: testnet block sync issue
* [#471](https://github.com/bnb-chain/greenfield/pull/471) fix: some issues in challenge module
NA
* NA
=> release: prepare for release v0.2.5-alpha.3

.github/workflows/build.yml, .github/workflows/docker-release.yml, .github/workflows/gosec.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/tests.yml
cleaning up unused tokens for ci jobs
n/a
n/a
* ci
=> chore: cleaning up ci jobs

CHANGELOG.md, go.mod, go.sum
This is a maintenance release to update the cosmos-sdk dependency to the latest version.
To update the cosmos-sdk dependency  
none
none
=> release: draft release for v0.2.6

x/payment/keeper/stream_record.go
Add deposit event for automatic deposit, it will make the offchain service easier. 
Add event
NA
* emit event
=> chore: add deposit event for user account

go.mod, go.sum
Update greenfield cosmos sdk to the `develop` version.
Update go mod
NA
* go.mod
=> chore: update cosmos-sdk version

go.mod, go.sum, swagger/static/swagger.yaml
update cosmos-sdk and cometbft to the latest `develop` branch.
make all developing changes to the latest.
N/A
* go.mod
=> chore: update cosmos-sdk and cometbft

app/upgrade.go, go.mod, go.sum
This pr will introduce the `Eddystone` upgrade.
Introduce the `Eddystone` upgrade.
n/a
* introduce the `Eddystone` upgrade
=> feat: introduce the Eddystone upgrade

x/storage/types/message.go
This pr is to change max length limit of resource tags key value
Previous setting is not reasonable and we should adjust them.
* change max length limit of resource tags key value
N/A
=> chore: change max length limit of resource tags key value

go.mod, go.sum
bump cosmos-sdk to v1.2.0
n/a
n/a
* dep
no
=> chore: bump cosmos-sdk to v1.2.0

CHANGELOG.md, asset/configs/mainnet_config/app.toml, asset/configs/testnet_config/app.toml
=> fix: fix conflict

readme.md, x/permission/types/keys_test.go, x/storage/types/keys.go
This pr is to update the links in README and fix typos
N/A
N/A
=> chore: fix typo and update doc

x/storage/types/crosschain.go
modify permission package types
stay consistent with the contract definition
* modify permission package types
* ...
=> fix: modify permission package types

app/upgrade.go, deployment/localup/localup.sh, go.mod, go.sum
Define Pawnee upgrade
Define Pawnee upgrade
=> feat: define Pawnee upgrade

go.mod, go.sum
prepare for release v1.4.0, update cometbft and cosmos-sdk dependency
* prepare for release v1.4.0, update cometbft and cosmos-sdk dependency
=> feat: prepare for release v1.4.0, update cometbft and cosmos-sdk dependency

x/storage/keeper/abci.go
add a description of your changes here...
* ...
* ...
=> fix: disable discontinue on testnet

x/storage/keeper/keeper.go
remove copy object approval
N/A
N/A
* remove copy object approval
* N/A
=> fix: remove copy object approval

app/upgrade.go, e2e/tests/storage_rate_limit_test.go
This pr will add the `MsgSetBucketFlowRateLimit` in `Erdos` upgrade. 
Add the missing message.
n/a
* add MsgSetBucketFlowRateLimit in Erdos upgrade
n/a
=> fix: add MsgSetBucketFlowRateLimit in Erdos upgrade

app/upgrade.go, e2e/tests/storage_rate_limit_test.go, x/storage/keeper/cross_app_executor.go
sync develop to master
* ...
* ...
=> sync: sync develop to master

go.mod, go.sum
update the cosmos-sdk version to update the erdos upgrade height.
update the cosmos-sdk version to update the erdos upgrade height.
* ...
* ...
=> dep: update cosmos-sdk version

go.mod, go.sum
fix the go.mod import
* ...
* ...
=> fix: refine import

deployment/localup/localup.sh, e2e/core/basesuite.go, e2e/tests/storage_rate_limit_test.go, x/storage/keeper/keeper.go, x/storage/keeper/payment.go
Fix the paymaster deleting issue.
Fix the paymaster deleting issue.
n/a
* fix deleting issue for paymaster
n/a
=> fix: fix deleting issue for paymaster

app/upgrade.go, deployment/localup/localup.sh
add registerVeldUpgradeHandler
*N/A
*N/A
* add registerVeldUpgradeHandler
*N/A
=> fix: register Veld hardfork handler

app/upgrade.go
add a description of your changes here...
* ...
* ...
=> fix: ingore register channel error

app/upgrade.go, deployment/localup/localup.sh, docs/modules/billing-and-payment.md, docs/modules/virtual-group.md, go.mod, go.sum, proto/greenfield/permission/types.proto, readme.md, x/permission/types/types.pb.go, x/storage/keeper/cross_app_permission.go, x/storage/keeper/cross_app_permission_test.go, x/storage/keeper/keeper.go, x/storage/keeper/permission.go, x/storage/types/expected_keepers.go, x/storage/types/expected_keepers_mocks.go, x/virtualgroup/keeper/grpc_query.go
prepare for v1.9.0, introduces the Mongolian upgrade.
Changes:
Features: 
https://github.com/bnb-chain/greenfield/pull/639 feat: Support msg to create policy by cross chain
Fixes:
https://github.com/bnb-chain/greenfield/pull/638  fix: initial val for min value comparison should be large enough
https://github.com/bnb-chain/greenfield/pull/640 fix: broken links reroute from local repo to bnbchain docs
Docs:
https://github.com/bnb-chain/greenfield/pull/633 docs: replace docs link]
=> release: prepare for release v1.9.0

CHANGELOG.md, app/ante/utils_test.go, app/upgrade.go, go.mod, go.sum, x/bridge/types/message_transfer_out.go, x/challenge/keeper/bls_signed_msg.go
This pr is to fix the EIP712 signing issue and introduce a new hardfork Altai
* add new signing schema to fit metamask
=> feat: introduce the Altai upgrade
